# -*- coding: utf-8 -*-
"""PERFORMING KMEANS CLUSTERING ON GENE EXPRESSION DATA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lu0AmtvAgF9atdvGwJSuOT6LqJLw8rzB
"""

import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

#Reading dataset
data = pd.read_csv('DATAR1.csv')


labels = data['Class']
X = data.drop(columns=['Class'])  # Drop the 'Class' column

# Performing KMeans clustering
num_clusters = 3  # You can adjust the number of clusters
kmeans = KMeans(n_clusters=num_clusters, random_state=0)
data['cluster'] = kmeans.fit_predict(X)


plt.scatter(X['gene_0'], X['gene_1'], c=data['cluster'], cmap='viridis')
plt.xlabel('Gene 0 Expression')
plt.ylabel('Gene 1 Expression')
plt.title('KMeans Clustering of Gene Expression Data')
plt.show()



import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


data = pd.read_csv('DATAR1.csv')

correlation_matrix = data.corr()

#Plotting
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='viridis', center=0)
plt.title('Correlation Matrix')
plt.show()